### ISSUE TITLE
发现一个由来已久的bug

### ISSUE THREAD

**Issue by blacklips** [tudou527/zh-time-nlp#1]
测试用例  
 [
    '五点一分',
    '十点十分',
    '八点十七分',
    '早上八点五十九分',
    '晚上八点五十九分',
    '九点二十分',
    '两天后洗车',
    '十天后洗车',
    '十一点五十九分五十九秒',
    '十点五十九分五十九秒',
    '一点五十九分五十九秒',
    '2019-5-3 19:00',
    '2019-05-3 19:00',
    '2019-5-03 19:00',
    '2019-05-03 19:00',
    '没有时间点',
    'Hi，all。下周一下午三点开会',
    '周一开会',
    '周五开会',
    '下下周一开会',
    '6:30 起床',
    '明天6:30 起床',
    '6-3 春游',
    '6月3日 春游',
    '12-1 春游',
    '明天早上跑步',
    '本周日到下周日出差',
    '周四下午三点到五点开会',
    '昨天上午，第八轮中美战略与经济对话气候变化问题特别联合会议召开',
  ].forEach(str => console.log('"%s" => %s', str, nlp(str,{baseTime:"2019-10-31 19:00"})));

输出结果
"五点一分" => 2019-10-32 05:01:00
"十点十分" => 2019-10-31 22:10:00
"八点十七分" => 2019-10-31 20:17:00
"早上八点五十九分" => 2019-10-31 20:59:00
"晚上八点五十九分" => 2019-10-31 20:59:00
"九点二十分" => 2019-10-31 21:20:00
"两天后洗车" => 2019-11-02 08:00:00
"十天后洗车" => 2019-11-10 08:00:00
"十一点五十九分五十九秒" => 2019-10-31 23:59:59
"十点五十九分五十九秒" => 2019-10-31 22:59:59
"一点五十九分五十九秒" => 2019-10-32 01:59:59
"2019-5-3 19:00" => 2019-05-03 19:00:00
"2019-05-3 19:00" => 2019-09-05 19:00:00
"2019-5-03 19:00" => 2019-05-03 19:00:00
"2019-05-03 19:00" => 2019-09-05 19:00:00
"没有时间点" => null
"Hi，all。下周一下午三点开会" => 2019-11-04 15:00:00
"周一开会" => 2019-11-04 08:00:00
"周五开会" => 2019-11-01 08:00:00
"下下周一开会" => 2019-11-11 08:00:00
"6:30 起床" => 2019-10-32 06:30:00
"明天6:30 起床" => 2019-11-01 06:30:00
"6-3 春游" => 2019-06-03 08:00:00
"6月3日 春游" => 2019-06-03 08:00:00
"12-1 春游" => 2019-12-01 08:00:00
"明天早上跑步" => 2019-11-01 08:00:00
"本周日到下周日出差" => { startTime: '2019-11-03 08:00:00', endTime: '2019-11-10 08:00:00' }
"周四下午三点到五点开会" => { startTime: '2019-10-31 15:00:00', endTime: '2019-10-31 17:00:00' }
"昨天上午，第八轮中美战略与经济对话气候变化问题特别联合会议召开" => 2019-10-30 10:00:00

**Comment by tudou527** [comment]
@blacklips  眼拙，啥 bug？没看出来

**Comment by blacklips** [comment]
"五点一分" => 2019-10-32 05:01:00 
"一点五十九分五十九秒" => 2019-10-32 01:59:59

**Comment by tudou527** [comment]
还真是个离谱的 bug

**Comment by tudou527** [comment]
@blacklips  1.0.2
